#!/usr/bin/env bash
# Regenerate deploy/schema-bundle.sql from db/migrations/.
#
# The bundle is generated, never hand-edited: a hand-maintained copy of ten
# migrations drifts, and it drifts silently, and you find out on the one night
# you are deploying. `npm run deploy:check` fails if the committed bundle no
# longer matches the migrations.
set -euo pipefail
cd "$(dirname "$0")/.."
out=deploy/schema-bundle.sql

{
  cat <<'HEADER'
-- =============================================================================
-- FitOS — complete schema, migrations 0001 through 0010, in order.
--
-- GENERATED by deploy/build-bundle.sh. Do not edit. Edit the migrations and
-- regenerate: npm run deploy:bundle
--
-- PREREQUISITE: the two cluster roles must already exist. This file checks and
-- refuses rather than half-applying — see deploy/README.md, which explains why
-- fitos_svc needs BYPASSRLS and what your options are on a host that will not
-- grant it.
--
--     create role fitos_app nologin;
--     create role fitos_svc nologin bypassrls;
--
-- Run as the database owner, in one transaction. If any statement fails the
-- whole thing rolls back and you can fix and re-run from the top.
--
-- AFTER this file: seed the demo data with `npx tsx db/seed.ts` pointed at the
-- same database, with FITOS_ORG_HASH_SECRET and FITOS_IDENTITY_SECRET set to
-- the values that deployment will keep using. Changing either one afterwards
-- makes every stored phone hash unmatchable.
-- =============================================================================

begin;

do $preflight$
begin
  if not exists (select 1 from pg_roles where rolname = 'fitos_app') then
    raise exception 'role fitos_app does not exist — see deploy/README.md';
  end if;
  if not exists (select 1 from pg_roles where rolname = 'fitos_svc') then
    raise exception 'role fitos_svc does not exist — see deploy/README.md';
  end if;
  if not exists (select 1 from pg_roles where rolname = 'fitos_svc' and rolbypassrls) then
    raise exception
      'role fitos_svc exists but lacks BYPASSRLS. Seeding, identity resolution and '
      'the public report path all depend on it, and report_view_orphan_audit() '
      'refuses to run without it. See deploy/README.md before proceeding.';
  end if;
  if exists (select 1 from pg_roles where rolname = 'fitos_app' and rolbypassrls) then
    raise exception
      'role fitos_app has BYPASSRLS. It must not: it is the role every request '
      'runs as, and RLS is the only thing standing between tenants.';
  end if;
end $preflight$;

HEADER

  for f in db/migrations/*.sql; do
    printf -- '-- ═══════════════════════════════════════════════════════════════════════════\n'
    printf -- '-- %s\n' "$(basename "$f")"
    printf -- '-- ═══════════════════════════════════════════════════════════════════════════\n\n'
    cat "$f"
    printf '\n\n'
  done

  cat <<'FOOTER'
-- ─────────────────────────────────────────────────────────────────────────────
commit;

-- Sanity check. Run this after committing; it should report 29 tables and every
-- one of the RLS numbers non-zero.
--   select count(*) tables from pg_class c join pg_namespace n on n.oid=c.relnamespace
--    where n.nspname='public' and c.relkind='r';
--   select count(*) rls_forced from pg_class where relforcerowsecurity;
--   select count(*) policies from pg_policies where schemaname='public';
FOOTER
} > "$out"

echo "wrote $out ($(wc -l < "$out") lines from $(ls db/migrations/*.sql | wc -l) migrations)"
