-- =============================================================================
-- FitOS — complete schema, migrations 0001 through 0010, in order.
--
-- GENERATED by deploy/build-bundle.sh. Do not edit. Edit the migrations and
-- regenerate: npm run deploy:bundle
--
-- PREREQUISITE: the two cluster roles must already exist. This file checks and
-- refuses rather than half-applying — see deploy/README.md, which explains why
-- fitos_svc needs BYPASSRLS and what your options are on a host that will not
-- grant it.
--
--     create role fitos_app nologin;
--     create role fitos_svc nologin bypassrls;
--
-- Run as the database owner, in one transaction. If any statement fails the
-- whole thing rolls back and you can fix and re-run from the top.
--
-- AFTER this file: seed the demo data with `npx tsx db/seed.ts` pointed at the
-- same database, with FITOS_ORG_HASH_SECRET and FITOS_IDENTITY_SECRET set to
-- the values that deployment will keep using. Changing either one afterwards
-- makes every stored phone hash unmatchable.
-- =============================================================================

begin;

do $preflight$
begin
  if not exists (select 1 from pg_roles where rolname = 'fitos_app') then
    raise exception 'role fitos_app does not exist — see deploy/README.md';
  end if;
  if not exists (select 1 from pg_roles where rolname = 'fitos_svc') then
    raise exception 'role fitos_svc does not exist — see deploy/README.md';
  end if;
  if not exists (select 1 from pg_roles where rolname = 'fitos_svc' and rolbypassrls) then
    raise exception
      'role fitos_svc exists but lacks BYPASSRLS. Seeding, identity resolution and '
      'the public report path all depend on it, and report_view_orphan_audit() '
      'refuses to run without it. See deploy/README.md before proceeding.';
  end if;
  if exists (select 1 from pg_roles where rolname = 'fitos_app' and rolbypassrls) then
    raise exception
      'role fitos_app has BYPASSRLS. It must not: it is the role every request '
      'runs as, and RLS is the only thing standing between tenants.';
  end if;
end $preflight$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 0001_tenancy_and_identity.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- Stride Guide FitOS — 0001 · tenancy, identity, consent, authorization
-- Blueprint: docs/05-data-model.md §1–§12
--
-- Three independent controls, never collapsed into one flag:
--   IDENTITY       person_identity + identity_resolution   "is this the same person?"
--   CONSENT        consent_record                          "did they authorize this use?"
--   AUTHORIZATION  location_customer_access + RLS          "is this location allowed?"
-- =============================================================================

create extension if not exists pgcrypto;

-- ─────────────────────────────────────────────────────────── enums ──
create type org_type          as enum ('independent','chain','franchise','clinic','orthotics','enterprise','events');
create type org_plan          as enum ('pilot','design_partner','active','paused');
create type customer_access_default as enum ('creating_location','all_locations');
create type identity_participation  as enum ('none','resolution_only','portable_profile');
create type size_unit         as enum ('us','uk','eu');
create type retail_focus      as enum ('running','comfort','work','orthopedic','sporting_goods');
create type inventory_source  as enum ('none','csv','pos_export','api');
create type network_quality   as enum ('good','variable','poor');
create type user_role         as enum ('associate','manager','owner','org_admin');
create type identity_account_status as enum ('shadow','claimed','closed');
create type identification_method   as enum ('phone','name_dob','loyalty_id','anonymous');
create type resolution_state  as enum ('candidate_match','verified','linked','revoked');
create type resolution_actor  as enum ('system','customer','retailer','support');
create type verification_method as enum ('customer_confirmation','account_claim','support_review');
create type access_level      as enum ('full','fit_profile_only','none');
create type consent_scope     as enum ('organization','person');
create type consent_type      as enum ('fit_history_storage','receive_report','privacy_ack',
                                       'marketing_email','marketing_sms','identity_resolution',
                                       'portable_profile_share');
create type consent_method    as enum ('tablet_checkbox','verbal_attested','web_form','written','mystrideid_account');

-- ──────────────────────────────────────────────────── organization ──
create table organization (
  id                       uuid primary key default gen_random_uuid(),
  name                     text not null,
  legal_name               text,
  org_type                 org_type not null default 'independent',
  plan                     org_plan not null default 'pilot',
  -- Chain-wide recognition is opt-in. A retailer who has not thought about
  -- cross-location customer data does not accidentally get it.
  default_customer_access  customer_access_default not null default 'creating_location',
  identity_participation   identity_participation  not null default 'none',
  data_owner_terms_version text not null default 'terms-v0',
  settings                 jsonb not null default '{}'::jsonb,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz
);

create table location (
  id                uuid primary key default gen_random_uuid(),
  organization_id   uuid not null references organization(id) on delete cascade,
  name              text not null,
  address_line1     text, city text, region text, postal_code text, country text,
  phone             text not null,
  email             text not null,
  logo_url          text,
  timezone          text not null default 'America/Chicago',
  size_unit         size_unit not null default 'us',
  retail_focus      retail_focus[] not null default '{}',
  -- Phase 0 discovery capture (docs/09 §2) — these change the build, so they
  -- are columns, not notes in a doc somewhere.
  pos_system                   text,
  inventory_source             inventory_source,
  tracks_associate_attribution boolean,
  network_quality              network_quality,
  active            boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz
);
create index on location (organization_id);

create table app_user (
  id              uuid primary key default gen_random_uuid(),
  location_id     uuid not null references location(id) on delete cascade,
  organization_id uuid not null references organization(id) on delete cascade,
  first_name      text not null,
  last_name       text,
  role            user_role not null default 'associate',
  pin_hash        text,
  auth_user_id    uuid,
  active          boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create index on app_user (organization_id);

-- Staff who genuinely cover two doors. Grants access; does not change ownership.
create table user_location (
  user_id     uuid not null references app_user(id) on delete cascade,
  location_id uuid not null references location(id) on delete cascade,
  primary key (user_id, location_id)
);

-- ────────────────────────────────────────────────── person_identity ──
-- Global, optional, deliberately almost empty. No name, phone, email, fit data
-- or purchase history: a global table holding contact details for every
-- customer of every retailer would be the most attractive breach target in the
-- company. This one is close to worthless on its own, which is the design.
create table person_identity (
  id                   uuid primary key default gen_random_uuid(),
  identity_lookup_hash bytea not null,
  identity_key_version smallint not null default 1,
  account_status       identity_account_status not null default 'shadow',
  auth_user_id         uuid,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz
);
create unique index on person_identity (identity_lookup_hash, identity_key_version);

-- ─────────────────────────────────────────── organization_customer ──
-- What an associate means by "customer": the retailer relationship.
create table organization_customer (
  id                     uuid primary key default gen_random_uuid(),
  organization_id        uuid not null references organization(id) on delete cascade,
  created_at_location_id uuid not null references location(id),
  -- Nullable, and null is the normal state. Day 1 never sets it.
  person_identity_id     uuid references person_identity(id),
  local_customer_number  integer not null,
  first_name             text,
  last_name              text,
  -- HMAC under the ORGANIZATION's key, not a global one: with one global key
  -- two retailers' rows for the same person would produce identical hashes,
  -- which would let the platform correlate customers across retailers as a
  -- silent side effect of the schema.
  phone_lookup_hash      bytea,
  phone_encrypted        bytea,
  phone_last4            text,
  phone_key_version      smallint,
  email_lookup_hash      bytea,
  email_encrypted        bytea,
  age_range              text,
  is_minor               boolean not null default false,
  identification_method  identification_method not null default 'phone',
  anonymous              boolean not null default false,
  notes                  text,
  deleted_at             timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz,
  constraint identified_customer_has_name
    check (anonymous or (first_name is not null and last_name is not null))
);
create unique index organization_customer_phone_key
  on organization_customer (organization_id, phone_lookup_hash)
  where phone_lookup_hash is not null and deleted_at is null;
create unique index organization_customer_number_key
  on organization_customer (organization_id, local_customer_number);

-- Per-organization customer numbering ("Customer #472").
create or replace function assign_local_customer_number() returns trigger as $$
begin
  if new.local_customer_number is null or new.local_customer_number = 0 then
    select coalesce(max(local_customer_number), 0) + 1
      into new.local_customer_number
      from organization_customer
     where organization_id = new.organization_id;
  end if;
  return new;
end $$ language plpgsql;

create trigger organization_customer_number
  before insert on organization_customer
  for each row execute function assign_local_customer_number();

-- ──────────────────────────────────────────── identity_resolution ──
-- A stateful resolution layer, not a link table. Two identical hashed phone
-- numbers must never cause two retailers to start sharing a customer history.
create table identity_resolution (
  id                       uuid primary key default gen_random_uuid(),
  organization_customer_id uuid not null references organization_customer(id) on delete cascade,
  person_identity_id       uuid not null references person_identity(id) on delete cascade,
  state                    resolution_state not null default 'candidate_match',
  evidence                 jsonb not null default '{}'::jsonb,
  proposed_by              resolution_actor not null default 'system',
  verified_by              verification_method,
  verified_at              timestamptz,
  revoked_at               timestamptz,
  revoked_reason           text,
  state_history            jsonb not null default '[]'::jsonb,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz,
  -- verified/linked require an actual verification event; the system may never
  -- promote its own guess.
  constraint verified_requires_method
    check (state in ('candidate_match','revoked') or verified_by is not null)
);
create unique index on identity_resolution (organization_customer_id, person_identity_id);

-- ───────────────────────────────────────── location_customer_access ──
-- Authorization, not ownership: grantable, revocable, auditable, per-location.
create table location_customer_access (
  id                       uuid primary key default gen_random_uuid(),
  -- Denormalized deliberately: this table's RLS policy must not reference
  -- organization_customer, whose own policy calls app_can_access_customer().
  -- Without this column the two policies recurse into each other.
  organization_id          uuid not null references organization(id) on delete cascade,
  organization_customer_id uuid not null references organization_customer(id) on delete cascade,
  location_id              uuid not null references location(id) on delete cascade,
  access_level             access_level not null default 'full',
  granted_by_user_id       uuid references app_user(id),
  granted_at               timestamptz not null default now(),
  revoked_at               timestamptz,
  reason                   text
);
create unique index location_customer_access_key
  on location_customer_access (organization_customer_id, location_id)
  where revoked_at is null;

-- Grant per organization policy at creation.
create or replace function grant_default_customer_access() returns trigger as $$
declare
  policy customer_access_default;
begin
  select default_customer_access into policy
    from organization where id = new.organization_id;

  if policy = 'all_locations' then
    insert into location_customer_access (organization_id, organization_customer_id, location_id)
    select new.organization_id, new.id, l.id
      from location l where l.organization_id = new.organization_id;
  else
    insert into location_customer_access (organization_id, organization_customer_id, location_id)
    values (new.organization_id, new.id, new.created_at_location_id);
  end if;
  return new;
end $$ language plpgsql;

create trigger organization_customer_default_access
  after insert on organization_customer
  for each row execute function grant_default_customer_access();

-- ─────────────────────────────────────────────────── consent_record ──
create table consent_record (
  id                       uuid primary key default gen_random_uuid(),
  scope                    consent_scope not null,
  organization_customer_id uuid references organization_customer(id) on delete cascade,
  person_identity_id       uuid references person_identity(id) on delete cascade,
  location_id              uuid references location(id),
  type                     consent_type not null,
  granted                  boolean not null,
  scope_detail             jsonb,
  consent_text_version     text not null,
  privacy_policy_version   text not null,
  method                   consent_method not null,
  captured_by_user_id      uuid references app_user(id),
  captured_at              timestamptz not null default now(),
  constraint consent_scope_subject check (
    (scope = 'organization' and organization_customer_id is not null) or
    (scope = 'person'       and person_identity_id is not null)
  )
);
create index on consent_record (organization_customer_id, type, captured_at desc);

-- Latest state per subject and type. Revocation appends; nothing is updated.
create view consent_current as
select distinct on (scope, organization_customer_id, person_identity_id, type)
       scope, organization_customer_id, person_identity_id, type, granted,
       consent_text_version, privacy_policy_version, captured_at
  from consent_record
 order by scope, organization_customer_id, person_identity_id, type, captured_at desc;


-- ═══════════════════════════════════════════════════════════════════════════
-- 0002_fitting_and_catalog.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- Stride Guide FitOS — 0002 · fitting session, canonical features, catalog
-- Blueprint: docs/05-data-model.md §13–§25
-- =============================================================================

create type session_status    as enum ('draft','in_progress','completed','voided');
create type void_reason       as enum ('test','mistaken_start','customer_withdrew','duplicate');
create type feature_source    as enum ('manual','sensor_derived','intake_inferred','imported','default');
create type override_reason   as enum ('disagrees_with_observation','poor_capture','customer_input','other');
create type evidence_strength as enum ('high','moderate','low');
create type rec_override_reason as enum ('customer_preference','associate_judgment','not_in_stock','budget','other');
create type outcome_kind      as enum ('purchased','purchased_other','considering','no_purchase','ordered');
create type follow_up_status  as enum ('scheduled','done','snoozed','cancelled');
create type capture_type      as enum ('static_stance','weight_shift','walk');
create type device_status     as enum ('provisioned','shipped','installed','rma','retired');
create type feedback_type     as enum ('bug','confusing','too_slow','wrong_recommendation','idea','praise');

-- ─────────────────────────────────────────────────── fitting_session ──
create table fitting_session (
  id                        uuid primary key default gen_random_uuid(),
  organization_id           uuid not null references organization(id) on delete cascade,
  location_id               uuid not null references location(id),
  organization_customer_id  uuid references organization_customer(id) on delete set null,
  user_id                   uuid not null references app_user(id),
  status                    session_status not null default 'draft',
  void_reason               void_reason,
  visit_number              integer,
  started_at                timestamptz not null default now(),
  completed_at              timestamptz,
  time_to_recommendation_ms integer,

  -- intake (1:1 with the session, always written and read together)
  shopping_purpose       text,
  current_shoe_problem   text[] not null default '{}',
  discomfort_area        text[] not null default '{}',
  discomfort_timing      text,
  activity_level         text,
  standing_hours_per_day text,
  current_shoe_brand     text,
  current_shoe_model     text,
  current_shoe_age       text,
  fit_priority           text[] not null default '{}',
  previous_return_reason text,
  uses_orthotics         text,
  shoe_wear_concern      text,
  intake_notes           text,
  need_summary           text,
  risk_flags             text[] not null default '{}',

  device_id                 text,
  draft_saved_at            timestamptz,
  draft_synced_at           timestamptz,
  assessment_schema_version text not null default 'assessment-1.0.0',
  created_at                timestamptz not null default now(),
  updated_at                timestamptz,
  -- Only completed sessions are historical fittings.
  constraint completed_has_timestamp
    check (status <> 'completed' or completed_at is not null)
);
create index on fitting_session (organization_customer_id, completed_at desc);
create index on fitting_session (location_id, status);

-- ──────────────────────────────────────────────────────── assessment ──
-- Human observation. One input to the feature model, not the model itself.
create table assessment (
  id                 uuid primary key default gen_random_uuid(),
  fitting_session_id uuid not null unique references fitting_session(id) on delete cascade,
  size_left          numeric(4,1),
  size_right         numeric(4,1),
  size_unit          size_unit not null default 'us',
  width              text,
  width_asymmetry    boolean not null default false,
  arch_type          text,
  foot_shape         text[] not null default '{}',
  pronation_tendency text,
  heel_slip_risk     text,
  toe_box_issue      text[] not null default '{}',
  wear_pattern       text,
  balance_concern    text,
  pressure_concern   text[] not null default '{}',
  -- the fitter's own call, captured before the engine's output is shown
  assoc_support_level    text,
  assoc_cushioning_level text,
  assoc_category         text,
  assoc_insole           text,
  assessment_notes   text,
  measured_at        timestamptz not null default now()
);

-- ─────────────────────────────────────────── canonical fit features ──
-- Manual observation and sensor derivation converge here. Everything below
-- this table survives the hardware unchanged.
create table fitting_feature (
  id                  uuid primary key default gen_random_uuid(),
  fitting_session_id  uuid not null references fitting_session(id) on delete cascade,
  feature_key         text not null,
  value_categorical   text,
  value_numeric       numeric,
  unit                text,
  -- provenance is first-class, not a loose jsonb blob
  source_type         feature_source not null,
  source_record_id    uuid,
  algorithm_version   text,
  quality             numeric check (quality is null or (quality >= 0 and quality <= 1)),
  captured_at         timestamptz not null default now(),
  overridden_by_user_id uuid references app_user(id),
  override_reason     override_reason,
  superseded_by       uuid references fitting_feature(id),
  constraint feature_has_a_value
    check (value_categorical is not null or value_numeric is not null)
);
create unique index fitting_feature_current_key
  on fitting_feature (fitting_session_id, feature_key)
  where superseded_by is null;

-- The feature dictionary. Additive-only within a major version: new keys may
-- appear, existing keys never change meaning or lose enum values.
create table feature_schema_version (
  version      text primary key,
  definitions  jsonb not null,
  released_at  timestamptz not null default now()
);

-- ────────────────────────────────────────────── scan (hardware) ──
-- Reserved now, used later. Raw captures are immutable.
create table scan (
  id                  uuid primary key default gen_random_uuid(),
  fitting_session_id  uuid not null references fitting_session(id) on delete cascade,
  device_id           uuid,
  device_installation_id uuid,
  firmware_version    text not null,
  calibration_version text not null,
  hardware_revision   text not null,
  capture_type        capture_type not null,
  raw_uri             text not null,
  raw_checksum        text not null,
  sample_rate_hz      integer,
  frame_count         integer,
  total_load_measured numeric,
  capture_quality     numeric,
  captured_at         timestamptz not null default now()
);

create table scan_derivation (
  id                uuid primary key default gen_random_uuid(),
  scan_id           uuid not null references scan(id) on delete cascade,
  algorithm_version text not null,
  derived           jsonb not null,
  quality_metrics   jsonb,
  is_current        boolean not null default true,
  derived_at        timestamptz not null default now()
);
create unique index on scan_derivation (scan_id) where is_current;

-- ──────────────────────────────────────────────────── recommendation ──
create table recommendation (
  id                 uuid primary key default gen_random_uuid(),
  fitting_session_id uuid not null references fitting_session(id) on delete cascade,
  fit_profile        jsonb not null,
  flags              text[] not null default '{}',
  evidence_strength  evidence_strength not null,
  evidence_detail    jsonb not null,
  -- five stamps: an August 2026 recommendation stays reproducible after the
  -- engine changes in 2027
  recommendation_engine_version text not null,
  rule_set_version              text not null,
  catalog_version               text not null,
  feature_schema_version        text not null,
  assessment_schema_version     text not null,
  fired_rule_ids     text[] not null default '{}',
  feature_snapshot   jsonb not null,
  talking_points     text[] not null default '{}',
  rationale          text not null,
  products_considered uuid[] not null default '{}',
  products_avoided   text[] not null default '{}',
  overridden         boolean not null default false,
  override_fields    jsonb,
  override_reason    rec_override_reason,
  created_at         timestamptz not null default now()
);
create index on recommendation (fitting_session_id, created_at desc);

create table assessment_delta (
  id                 uuid primary key default gen_random_uuid(),
  fitting_session_id uuid not null unique references fitting_session(id) on delete cascade,
  previous_session_id uuid not null references fitting_session(id),
  interval_days      integer not null,
  changes            jsonb not null,
  material_change    boolean not null default false,
  narrative          text
);

-- ────────────────────────────────────────────────────────── catalog ──
create table product_model (
  id               uuid primary key default gen_random_uuid(),
  brand            text not null,
  model            text not null,
  variant          text,
  model_year       integer,
  category         text not null,
  use_case         text[] not null default '{}',
  support_level    text not null,
  cushioning_level text not null,
  toe_box_shape    text,
  heel_structure   text,
  flexibility      text,
  volume           text,
  drop_mm          integer,
  weight_g         integer,
  removable_insole boolean not null default true,
  safety_toe       boolean not null default false,
  slip_resistant   boolean not null default false,
  waterproof       boolean not null default false,
  best_for         text[] not null default '{}',
  avoid_for        text[] not null default '{}',
  msrp             numeric(8,2),
  data_source      text not null default 'curated',
  verified_at      timestamptz,
  catalog_version  text not null default 'catalog-1.0.0'
);
create unique index on product_model (brand, model, coalesce(variant,''), coalesce(model_year,0));

create table product_variant (
  id               uuid primary key default gen_random_uuid(),
  product_model_id uuid not null references product_model(id) on delete cascade,
  gender           text,
  size             numeric(4,1),
  width            text,
  colorway         text,
  upc              text,
  manufacturer_sku text
);
create index on product_variant (product_model_id);

create table location_inventory (
  id                 uuid primary key default gen_random_uuid(),
  location_id        uuid not null references location(id) on delete cascade,
  organization_id    uuid not null references organization(id) on delete cascade,
  product_model_id   uuid not null references product_model(id),
  widths_stocked     text[] not null default '{}',
  size_low           numeric(4,1),
  size_high          numeric(4,1),
  retailer_sku       text,
  retail_price       numeric(8,2),
  stocked            boolean not null default true,
  quantity           integer,
  source             text not null default 'manual',
  last_synced_at     timestamptz,
  notes              text
);
create unique index on location_inventory (location_id, product_model_id);

-- ────────────────────────────────────── outcome, report, follow-up ──
create table outcome (
  id                       uuid primary key default gen_random_uuid(),
  fitting_session_id       uuid not null unique references fitting_session(id) on delete cascade,
  outcome                  outcome_kind not null,
  purchased_model_id       uuid references product_model(id),
  purchased_size           numeric(4,1),
  recommended_vs_purchased text,
  insole_attached          boolean not null default false,
  insole_type              text,
  sale_value               numeric(10,2),
  returned                 boolean,
  return_reason            text,
  returned_at              timestamptz,
  satisfaction             text,
  recorded_at              timestamptz not null default now()
);

create table report (
  id                       uuid primary key default gen_random_uuid(),
  fitting_session_id       uuid not null references fitting_session(id) on delete cascade,
  organization_customer_id uuid references organization_customer(id) on delete cascade,
  report_version           integer not null default 1,
  template_version         text not null default 'report-1.0.0',
  -- hashed: a database read cannot mint a working link
  access_token_hash        bytea not null,
  expires_at               timestamptz not null,
  revoked_at               timestamptz,
  generated_at             timestamptz not null default now(),
  emailed_at               timestamptz,
  printed_at               timestamptz,
  content_snapshot         jsonb not null
);
create unique index on report (access_token_hash);
create index on report (fitting_session_id, report_version desc);

create table report_view (
  id               uuid primary key default gen_random_uuid(),
  report_id        uuid not null references report(id) on delete cascade,
  viewed_at        timestamptz not null default now(),
  user_agent_class text,
  referrer_class   text
);

create table follow_up (
  id                       uuid primary key default gen_random_uuid(),
  organization_id          uuid not null references organization(id) on delete cascade,
  location_id              uuid not null references location(id),
  organization_customer_id uuid references organization_customer(id) on delete cascade,
  fitting_session_id       uuid references fitting_session(id) on delete cascade,
  follow_up_reason         text not null,
  follow_up_due_at         timestamptz not null,
  follow_up_status         follow_up_status not null default 'scheduled',
  channel                  text not null default 'in_store_reminder',
  completed_by_user_id     uuid references app_user(id),
  response                 text,
  response_note            text
);
create index on follow_up (location_id, follow_up_status, follow_up_due_at);

-- ─────────────────────────────────────────────── device and feedback ──
create table device (
  id                          uuid primary key default gen_random_uuid(),
  serial                      text not null unique,
  hardware_revision           text not null,
  manufactured_at             timestamptz,
  public_key                  text,
  current_firmware_version    text,
  current_calibration_version text,
  status                      device_status not null default 'provisioned'
);

create table device_installation (
  id              uuid primary key default gen_random_uuid(),
  device_id       uuid not null references device(id) on delete cascade,
  organization_id uuid not null references organization(id) on delete cascade,
  location_id     uuid not null references location(id) on delete cascade,
  installed_at    timestamptz not null default now(),
  removed_at      timestamptz,
  host_machine_id text
);

create table device_health_event (
  id                  uuid primary key default gen_random_uuid(),
  device_id           uuid not null references device(id) on delete cascade,
  event_type          text not null,
  firmware_version    text,
  calibration_version text,
  connectivity        text,
  signal_quality      numeric,
  component_status    jsonb,
  error_code          text,
  reported_at         timestamptz not null default now()
);
create index on device_health_event (device_id, reported_at desc);

create table pilot_feedback (
  id                 uuid primary key default gen_random_uuid(),
  organization_id    uuid not null references organization(id) on delete cascade,
  location_id        uuid references location(id),
  user_id            uuid references app_user(id),
  fitting_session_id uuid references fitting_session(id) on delete set null,
  type               feedback_type not null,
  screen             text,
  note               text,
  input_snapshot     jsonb,
  status             text not null default 'new',
  created_at         timestamptz not null default now()
);


-- ═══════════════════════════════════════════════════════════════════════════
-- 0003_rls.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- Stride Guide FitOS — 0003 · row-level security
-- Blueprint: docs/05-data-model.md §26, docs/09 Day 1 gate
--
-- Tenant context is carried in GUCs set per request:
--   app.organization_id · app.location_id · app.bypass_location_scope
-- On Supabase these are populated from JWT claims by the same helper functions.
-- =============================================================================

-- Roles are cluster-level: see db/bootstrap_roles.sql, run once as superuser.

create or replace function app_current_org() returns uuid as $$
  select nullif(current_setting('app.organization_id', true), '')::uuid
$$ language sql stable;

create or replace function app_current_location() returns uuid as $$
  select nullif(current_setting('app.location_id', true), '')::uuid
$$ language sql stable;

-- Managers/owners viewing org-wide reporting. Never set for the floor app.
create or replace function app_bypass_location_scope() returns boolean as $$
  select coalesce(nullif(current_setting('app.bypass_location_scope', true), ''), 'false')::boolean
$$ language sql stable;

-- Is the current location authorized for this customer? Authorization lives in
-- location_customer_access, never in a foreign key.
create or replace function app_can_access_customer(customer uuid) returns boolean as $$
  select app_bypass_location_scope() or exists (
    select 1 from location_customer_access a
     where a.organization_customer_id = customer
       and a.location_id = app_current_location()
       and a.revoked_at is null
       and a.access_level <> 'none'
  )
$$ language sql stable security definer;

-- ─────────────────────────────────────────── org-scoped tables ──
do $$
declare t text;
begin
  foreach t in array array[
    'location','app_user','organization_customer','fitting_session',
    'location_inventory','follow_up','pilot_feedback','device_installation'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('alter table %I force  row level security', t);
    execute format($f$
      create policy tenant_isolation on %I
        using (organization_id = app_current_org())
        with check (organization_id = app_current_org())
    $f$, t);
    execute format('grant select, insert, update, delete on %I to fitos_app, fitos_svc', t);
  end loop;
end $$;

alter table organization enable row level security;
alter table organization force  row level security;
create policy tenant_isolation on organization
  using (id = app_current_org()) with check (id = app_current_org());
grant select, update on organization to fitos_app, fitos_svc;

-- ─────────────────── customer: org isolation AND location authorization ──
drop policy tenant_isolation on organization_customer;
create policy tenant_isolation on organization_customer
  using (organization_id = app_current_org() and app_can_access_customer(id))
  with check (organization_id = app_current_org());

alter table location_customer_access enable row level security;
alter table location_customer_access force  row level security;
create policy tenant_isolation on location_customer_access
  using (organization_id = app_current_org())
  with check (organization_id = app_current_org());
grant select, insert, update on location_customer_access to fitos_app, fitos_svc;

-- ───────────────────────────── session children inherit the session ──
do $$
declare t text;
begin
  foreach t in array array[
    'assessment','fitting_feature','recommendation','assessment_delta',
    'outcome','report','scan','scan_derivation'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('alter table %I force  row level security', t);
    execute format('grant select, insert, update, delete on %I to fitos_app, fitos_svc', t);
  end loop;
end $$;

create policy tenant_isolation on assessment
  using (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()))
  with check (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()));
create policy tenant_isolation on fitting_feature
  using (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()))
  with check (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()));
create policy tenant_isolation on recommendation
  using (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()))
  with check (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()));
create policy tenant_isolation on assessment_delta
  using (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()))
  with check (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()));
create policy tenant_isolation on outcome
  using (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()))
  with check (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()));
create policy tenant_isolation on report
  using (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()))
  with check (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()));
create policy tenant_isolation on scan
  using (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()))
  with check (exists (select 1 from fitting_session s where s.id = fitting_session_id and s.organization_id = app_current_org()));
create policy tenant_isolation on scan_derivation
  using (exists (select 1 from scan sc join fitting_session s on s.id = sc.fitting_session_id
                  where sc.id = scan_id and s.organization_id = app_current_org()))
  with check (exists (select 1 from scan sc join fitting_session s on s.id = sc.fitting_session_id
                       where sc.id = scan_id and s.organization_id = app_current_org()));

-- ──────────────────────────────────────────────────── consent ──
alter table consent_record enable row level security;
alter table consent_record force  row level security;
create policy tenant_isolation on consent_record
  using (organization_customer_id is null or exists (
          select 1 from organization_customer c
           where c.id = organization_customer_id and c.organization_id = app_current_org()))
  with check (organization_customer_id is null or exists (
          select 1 from organization_customer c
           where c.id = organization_customer_id and c.organization_id = app_current_org()));
grant select, insert on consent_record to fitos_app, fitos_svc;

-- ─────────────────────────────── identity: no retailer-facing path ──
-- The application role cannot read person_identity or identity_resolution at
-- all. Resolution runs in an isolated service with its own credentials and its
-- own audit log; knowing two records are the same person must never become a
-- query a retailer's session can make.
alter table person_identity     enable row level security;
alter table person_identity     force  row level security;
alter table identity_resolution enable row level security;
alter table identity_resolution force  row level security;
grant select, insert, update on person_identity, identity_resolution to fitos_svc;
revoke all on person_identity, identity_resolution from fitos_app;

-- ──────────────────────────────── global catalog is shared, read-only ──
grant select on product_model, product_variant to fitos_app, fitos_svc;
grant select on consent_current to fitos_app, fitos_svc;
grant select, insert on report_view to fitos_app, fitos_svc;
grant select, insert on device_health_event to fitos_svc;
grant select on device to fitos_app, fitos_svc;
grant usage on schema public to fitos_app, fitos_svc;

-- The service role performs seeding, migrations-adjacent data work and identity
-- resolution. BYPASSRLS alone is not enough — it still needs table privileges,
-- and granting them explicitly is what keeps the separation auditable.
grant insert, update, delete, truncate on organization to fitos_svc;
grant delete, truncate on
  location, app_user, organization_customer, fitting_session, location_inventory,
  follow_up, pilot_feedback, device_installation, location_customer_access,
  consent_record, assessment, fitting_feature, recommendation, assessment_delta,
  outcome, report, scan, scan_derivation
  to fitos_svc;
grant insert, update, delete on product_model, product_variant to fitos_svc;
grant delete on person_identity, identity_resolution to fitos_svc;
grant insert, update, delete on device, feature_schema_version to fitos_svc;


-- ═══════════════════════════════════════════════════════════════════════════
-- 0004_fk_delete_rules.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- 0004 · delete rules on location references
--
-- Found by re-running the isolation suite against seeded application data:
-- deleting an organization cascaded to its locations, but consent_record,
-- fitting_session, follow_up and pilot_feedback referenced location with no
-- delete rule, so the cascade hit a foreign-key error. Tenant teardown has to
-- work — it is how erasure requests and pilot resets are honoured.
--
-- consent_record keeps its row and loses the pointer: a consent event happened,
-- and the record of it should not disappear because a store closed.
-- =============================================================================

alter table consent_record  drop constraint consent_record_location_id_fkey,
  add constraint consent_record_location_id_fkey
  foreign key (location_id) references location(id) on delete set null;

alter table fitting_session drop constraint fitting_session_location_id_fkey,
  add constraint fitting_session_location_id_fkey
  foreign key (location_id) references location(id) on delete cascade;

alter table follow_up       drop constraint follow_up_location_id_fkey,
  add constraint follow_up_location_id_fkey
  foreign key (location_id) references location(id) on delete cascade;

alter table pilot_feedback  drop constraint pilot_feedback_location_id_fkey,
  add constraint pilot_feedback_location_id_fkey
  foreign key (location_id) references location(id) on delete set null;

alter table organization_customer drop constraint organization_customer_created_at_location_id_fkey,
  add constraint organization_customer_created_at_location_id_fkey
  foreign key (created_at_location_id) references location(id) on delete cascade;

alter table report drop constraint report_organization_customer_id_fkey,
  add constraint report_organization_customer_id_fkey
  foreign key (organization_customer_id) references organization_customer(id) on delete cascade;

-- Same class of problem on user references: attribution should survive a
-- staff record being removed, so these null out rather than block.
alter table consent_record drop constraint consent_record_captured_by_user_id_fkey,
  add constraint consent_record_captured_by_user_id_fkey
  foreign key (captured_by_user_id) references app_user(id) on delete set null;

alter table fitting_session drop constraint fitting_session_user_id_fkey,
  add constraint fitting_session_user_id_fkey
  foreign key (user_id) references app_user(id) on delete cascade;

alter table follow_up drop constraint follow_up_completed_by_user_id_fkey,
  add constraint follow_up_completed_by_user_id_fkey
  foreign key (completed_by_user_id) references app_user(id) on delete set null;

alter table pilot_feedback drop constraint pilot_feedback_user_id_fkey,
  add constraint pilot_feedback_user_id_fkey
  foreign key (user_id) references app_user(id) on delete set null;

alter table location_customer_access drop constraint location_customer_access_granted_by_user_id_fkey,
  add constraint location_customer_access_granted_by_user_id_fkey
  foreign key (granted_by_user_id) references app_user(id) on delete set null;

alter table fitting_feature drop constraint fitting_feature_overridden_by_user_id_fkey,
  add constraint fitting_feature_overridden_by_user_id_fkey
  foreign key (overridden_by_user_id) references app_user(id) on delete set null;


-- ═══════════════════════════════════════════════════════════════════════════
-- 0005_consent_person_scope.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- 0005 · consent_record — close the person-scope read hole
--
-- The previous policy admitted "organization_customer_id is null or ...", which
-- left every scope='person' row readable by every tenant. Those rows carry
-- person_identity_id, and the application role is forbidden from reading
-- person_identity itself (see 0003) — so this leaked precisely what that
-- prohibition exists to protect: which identity, what was consented to, whether
-- it was granted or withdrawn, when, and by what method.
--
-- Organization-scoped rows: unchanged, scoped through their customer.
-- Person-scoped rows: scoped through the location that captured them.
--
-- Scoped rather than hidden outright. Hiding them from the application role is
-- the tighter reading of "identity belongs to resolution, not to retailers",
-- but the with-check would then reject any person-scoped consent written from
-- the tablet — and identity_resolution and portable_profile_share are consents
-- a customer plausibly grants mid-fitting, under the app role. A row with no
-- location resolves to visible-to-nobody, which is the correct failure
-- direction.
-- =============================================================================

drop policy tenant_isolation on consent_record;

create policy tenant_isolation on consent_record
  using (
    case
      when organization_customer_id is not null then exists (
        select 1 from organization_customer c
         where c.id = organization_customer_id
           and c.organization_id = app_current_org())
      else exists (
        select 1 from location l
         where l.id = location_id
           and l.organization_id = app_current_org())
    end)
  with check (
    case
      when organization_customer_id is not null then exists (
        select 1 from organization_customer c
         where c.id = organization_customer_id
           and c.organization_id = app_current_org())
      else exists (
        select 1 from location l
         where l.id = location_id
           and l.organization_id = app_current_org())
    end);


-- ═══════════════════════════════════════════════════════════════════════════
-- 0006_audit_log.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- 0006 · audit_log
--
-- Append-only, tenant-scoped record of consequential actions. Built now because
-- identity merge (a later step) is not reconstructible without it: a merge that
-- leaves no trail cannot be reversed or explained.
--
-- CLAUDE.md: "Log identifiers, not people." Nothing in here is meant to hold a
-- phone number, an email, a name, an address, or a raw token — and three
-- separate mechanisms are used to keep it that way, because a log is exactly
-- the place where PII accumulates by accident.
-- =============================================================================

-- ── Metadata safety: reject PII-shaped keys at any depth ────────────────────
-- A check constraint rather than application validation alone. The helper in
-- src/lib/db/audit.ts checks the same thing, but the helper can be bypassed and
-- the constraint cannot.
create or replace function audit_metadata_has_banned_key(m jsonb)
returns boolean as $$
declare k text; v jsonb;
begin
  if jsonb_typeof(m) = 'object' then
    for k, v in select * from jsonb_each(m) loop
      if lower(k) ~ '(phone|mobile|email|name|address|street|city|postal|zip|token|secret|password|passwd|pepper|ssn|dob|birth)' then
        return true;
      end if;
      if audit_metadata_has_banned_key(v) then return true; end if;
    end loop;
  elsif jsonb_typeof(m) = 'array' then
    for v in select * from jsonb_array_elements(m) loop
      if audit_metadata_has_banned_key(v) then return true; end if;
    end loop;
  end if;
  return false;
end $$ language plpgsql immutable;

-- The pattern is deliberately broad. It rejects `location_name` and
-- `product_name` as readily as `customer_name`, and that is the intended
-- trade-off: audit metadata carries ids and enums, so the fix for a rejected
-- key is to log `location_id` instead of `location_name`, not to loosen the
-- rule. A false positive is a rename; a false negative is a name in a log.

create table audit_log (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organization(id) on delete cascade,

  -- No foreign keys on the actor or location. Every other table here uses them,
  -- but an audit row must outlive the user or location it names: an
  -- `on delete set null` would erase the actor from the record of their own
  -- action, which is the one thing this table exists to remember.
  location_id     uuid,
  actor_user_id   uuid,
  actor_type      text not null default 'user'
                    check (actor_type in ('user', 'service', 'system')),

  -- namespace.event — e.g. customer_identity.merge_completed. Format is
  -- constrained; the vocabulary is not, because a whitelist here means a
  -- migration for every new event type. The authoritative list of names lives
  -- in src/lib/db/audit.ts.
  action          text not null check (action ~ '^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$'),

  -- What was acted on, and (optionally) what it was acted on *with*. For a
  -- merge: subject is the surviving customer, target is the one merged away.
  subject_type    text not null check (subject_type ~ '^[a-z][a-z0-9_]*$'),
  subject_id      uuid,
  target_type     text check (target_type ~ '^[a-z][a-z0-9_]*$'),
  target_id       uuid,

  correlation_id  uuid,   -- groups events belonging to one operation
  request_id      text constraint audit_log_request_id_len check (length(request_id) <= 128),

  metadata        jsonb not null default '{}'::jsonb
                    constraint audit_log_metadata_is_object
                      check (jsonb_typeof(metadata) = 'object')
                    constraint audit_log_metadata_no_pii_keys
                      check (not audit_metadata_has_banned_key(metadata)),

  -- clock_timestamp(), not now(). now() is transaction start time, so two
  -- events written in one transaction would share a timestamp exactly. Still
  -- entirely server-generated: the column is excluded from the INSERT grant
  -- below, so no caller can supply or backdate it.
  created_at      timestamptz not null default clock_timestamp(),

  -- Ordering is `seq`, not `created_at`. clock_timestamp() is microsecond
  -- resolution, and two inserts in one transaction can and do land in the same
  -- microsecond — observed intermittently in AU10 before this column existed. A
  -- timestamp answers "when"; only a sequence answers "in what order", and a
  -- merge trail (requested → completed → reverted) is worthless without that.
  -- GENERATED ALWAYS refuses a caller-supplied value outright.
  seq             bigint generated always as identity
);

create unique index audit_log_seq on audit_log (seq);

create index audit_log_org_time     on audit_log (organization_id, created_at desc);
create index audit_log_subject      on audit_log (subject_type, subject_id);
create index audit_log_correlation  on audit_log (correlation_id) where correlation_id is not null;

-- ── RLS ─────────────────────────────────────────────────────────────────────
alter table audit_log enable row level security;
alter table audit_log force  row level security;

-- Two policies with explicit verbs rather than one FOR ALL policy. Permissive
-- policies are OR'd, so a FOR ALL policy would silently authorise UPDATE and
-- DELETE the moment anyone granted them. With no policy naming those verbs,
-- RLS denies them even if the grant is added later.
create policy audit_log_select on audit_log
  for select using (organization_id = app_current_org());

create policy audit_log_insert on audit_log
  for insert with check (organization_id = app_current_org());

-- ── Grants ──────────────────────────────────────────────────────────────────
-- Column-level INSERT, deliberately: `id` and `created_at` are absent, so the
-- server generates both and no caller can backdate an audit row. No UPDATE and
-- no DELETE grant to anyone — append-only is enforced by privilege and by the
-- absence of a policy, not by convention.
grant select on audit_log to fitos_app, fitos_svc;
grant insert (organization_id, location_id, actor_user_id, actor_type,
              action, subject_type, subject_id, target_type, target_id,
              correlation_id, request_id, metadata)
  on audit_log to fitos_app, fitos_svc;


-- ═══════════════════════════════════════════════════════════════════════════
-- 0007_report_view_scope.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- 0007 · report_view — tenant scope, RLS, and an orphan preflight
--
-- report_view is the access log for customer reports: who opened a report link
-- and when. It had no organization_id and no RLS, so it was the one table where
-- viewing patterns crossed the tenant boundary.
--
-- It also had two rows referencing reports that no longer existed, behind a
-- VALIDATED cascade foreign key where that should be impossible. The provenance
-- was never established. That is exactly why the sweep below is gated rather
-- than automatic: an access log quietly losing rows is a bigger problem than the
-- migration it is blocking, and deleting the evidence is the wrong first move.
-- =============================================================================

-- ── Preflight, as a permanent callable ──────────────────────────────────────
-- A function rather than a one-off script: the same integrity question is worth
-- asking again later, and ops can run it against a real database without
-- running a migration.
create or replace function report_view_orphan_audit()
returns table (check_name text, n bigint) as $fn$
begin
  -- Refuse to answer where the answer would be misleading. RLS on report_view is
  -- FORCEd, which applies to the table owner too, so a caller without BYPASSRLS
  -- counts only the rows it can already see — and reports zero orphans on a
  -- database full of them. An integrity check that inherits the visibility rules
  -- it is auditing is worse than no check, because it reads as reassurance.
  --
  -- The condition is on FORCE being set rather than on the role alone, so the
  -- preflight below still runs during this migration, before RLS is enabled.
  if exists (select 1 from pg_class where relname = 'report_view' and relforcerowsecurity)
     and not exists (select 1 from pg_roles where rolname = current_user and rolbypassrls) then
    raise exception
      'report_view_orphan_audit() must run as a role that bypasses RLS (set role fitos_svc). '
      'Called as %, it would count only visible rows and under-report orphans.', current_user;
  end if;

  return query
    select 'total_rows', count(*)::bigint from report_view
    union all
    select 'missing_report_id', count(*)::bigint from report_view where report_id is null
    union all
    select 'report_does_not_exist', count(*)::bigint
      from report_view rv left join report r on r.id = rv.report_id
     where rv.report_id is not null and r.id is null
    union all
    select 'scope_unresolvable', count(*)::bigint
      from report_view rv
      join report r on r.id = rv.report_id
      left join fitting_session s on s.id = r.fitting_session_id
     where s.id is null or s.organization_id is null
    union all
    select 'report_expired_or_revoked', count(*)::bigint
      from report_view rv join report r on r.id = rv.report_id
     where r.revoked_at is not null or r.expires_at <= now();
end $fn$ language plpgsql stable;

revoke execute on function report_view_orphan_audit() from public;
grant execute on function report_view_orphan_audit() to fitos_svc;

comment on function report_view_orphan_audit() is
  'Integrity counts for report_view. Run before any cleanup. Rows that cannot '
  'resolve an organization cannot be shown to one, but they are still evidence.';

-- ── Report, always ──────────────────────────────────────────────────────────
do $$
declare rec record;
begin
  raise notice '--- report_view preflight ---';
  for rec in select * from report_view_orphan_audit() loop
    raise notice '  % = %', rpad(rec.check_name, 26), rec.n;
  end loop;
end $$;

-- ── Scope column, backfilled only where it can be proven ────────────────────
alter table report_view add column organization_id uuid;

update report_view rv
   set organization_id = s.organization_id
  from report r
  join fitting_session s on s.id = r.fitting_session_id
 where r.id = rv.report_id;

-- ── Gate ────────────────────────────────────────────────────────────────────
-- Anything still null could not be traced to an organization through
-- report → fitting_session. Inventing a tenant for it would be worse than
-- failing: it would file one retailer's access record under another's.
do $$
declare unresolved bigint;
begin
  select count(*) into unresolved from report_view where organization_id is null;
  if unresolved = 0 then
    raise notice 'report_view: all rows resolved to an organization';
    return;
  end if;

  if coalesce(current_setting('fitos.orphan_sweep', true), '') <> 'approved' then
    raise exception
      'report_view has % row(s) that cannot resolve an organization. Migration stopped. '
      'Inspect them first:  select id, report_id, viewed_at from report_view where organization_id is null; '
      'On a local or demo database, re-run with:  psql -c "set fitos.orphan_sweep = ''approved''" '
      'or PGOPTIONS="-c fitos.orphan_sweep=approved". On a real database, do not sweep until the rows '
      'are explained — see docs/05, "report_view integrity".', unresolved;
  end if;

  raise notice 'report_view: sweeping % unresolvable row(s) under explicit approval', unresolved;
  delete from report_view where organization_id is null;
end $$;

alter table report_view alter column organization_id set not null;
alter table report_view add constraint report_view_organization_id_fkey
  foreign key (organization_id) references organization(id) on delete cascade;

create index report_view_org_time on report_view (organization_id, viewed_at desc);

-- ── RLS ─────────────────────────────────────────────────────────────────────
alter table report_view enable row level security;
alter table report_view force  row level security;

-- Explicit verbs, as with audit_log: a FOR ALL policy would authorise UPDATE and
-- DELETE the moment anyone granted them. An access log is append-only.
create policy report_view_select on report_view
  for select using (organization_id = app_current_org());
create policy report_view_insert on report_view
  for insert with check (organization_id = app_current_org());

-- The app role reads its own organization's access log and never writes one.
-- Writing happens on the public report path, which runs as fitos_svc because the
-- viewer is anonymous and has no tenant context to satisfy.
grant select on report_view to fitos_app, fitos_svc;
grant insert (report_id, organization_id, user_agent_class, referrer_class)
  on report_view to fitos_svc;


-- ═══════════════════════════════════════════════════════════════════════════
-- 0008_identity_merge.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- 0008 · identity merge primitive
--
-- Duplicates happen: the customer who gave a mobile in March and a landline in
-- June is two records. This resolves them without losing fitting history,
-- consent history, reports, follow-ups or auditability.
--
-- The merged-away record is NEVER deleted. Two schema facts make that
-- structural rather than stylistic:
--
--   1. phone_lookup_hash lives on organization_customer as a column, so the
--      survivor cannot absorb the other record's number — there is nowhere to
--      put it. The tombstone is the only thing that can carry that hash and
--      redirect a lookup on it.
--   2. fitting_session.organization_customer_id is ON DELETE SET NULL while the
--      other five references cascade, so deleting a customer would orphan their
--      fitting history rather than remove it.
-- =============================================================================

alter table organization_customer
  add column merged_into_customer_id uuid references organization_customer(id),
  add column merged_at               timestamptz;

alter table organization_customer
  add constraint organization_customer_merge_consistent
    check ((merged_into_customer_id is null) = (merged_at is null)),
  add constraint organization_customer_no_self_merge
    check (merged_into_customer_id is null or merged_into_customer_id <> id);

create index organization_customer_merged
  on organization_customer (merged_into_customer_id)
  where merged_into_customer_id is not null;

-- ── Resolver ────────────────────────────────────────────────────────────────
-- One hop, not recursive: chains are refused at merge time, so a second hop
-- would be unreachable code pretending to be robustness. Invoker rights, so a
-- foreign tenant's id resolves to itself and then fails the usual policies.
create or replace function app_resolve_customer(candidate uuid) returns uuid as $$
  select coalesce(
    (select merged_into_customer_id from organization_customer
      where id = candidate and merged_into_customer_id is not null),
    candidate)
$$ language sql stable;

-- ── A fitting may never attach to a tombstone ───────────────────────────────
-- Enforced by trigger rather than in application code: this must hold for the
-- seed, for a psql session, and for any future write path, not only for the one
-- function that exists today.
create or replace function fitting_session_reject_tombstone() returns trigger as $$
begin
  if new.organization_customer_id is not null
     and exists (select 1 from organization_customer
                  where id = new.organization_customer_id
                    and merged_into_customer_id is not null) then
    raise exception
      'customer % has been merged into another record; start the fitting on the surviving customer',
      new.organization_customer_id
      using errcode = 'integrity_constraint_violation';
  end if;
  return new;
end $$ language plpgsql;

create trigger fitting_session_no_tombstone
  before insert or update of organization_customer_id on fitting_session
  for each row execute function fitting_session_reject_tombstone();

-- ── Effective consent, per type, for one or two customers ───────────────────
-- Same resolution rule as the Step 4 chokepoint: latest row wins, and at equal
-- captured_at a withdrawal beats a grant. Duplicated here rather than shared
-- because the chokepoint answers for one customer and this must answer for the
-- union of two.
create or replace function app_effective_consent(customers uuid[])
returns table (consent consent_type, granted boolean) as $$
  select distinct on (type) type, granted
    from consent_record
   where organization_customer_id = any(customers)
   order by type, captured_at desc, granted asc
$$ language sql stable;

-- ── The merge ───────────────────────────────────────────────────────────────
create or replace function app_merge_customer(
  loser uuid, winner uuid, actor uuid, correlation uuid,
  confirm_marketing_flip boolean default false)
returns jsonb as $$
declare
  org_loser uuid; org_winner uuid;
  loser_merged uuid; winner_merged uuid;
  manifest jsonb; flips text[]; withdrawals text[]; marketing_flips text[];
begin
  if loser = winner then
    raise exception 'cannot merge a customer into itself';
  end if;

  select organization_id, merged_into_customer_id into org_loser, loser_merged
    from organization_customer where id = loser;
  select organization_id, merged_into_customer_id into org_winner, winner_merged
    from organization_customer where id = winner;

  -- One message for absent, invisible, and foreign. A distinct "belongs to
  -- another organization" error would confirm that an id exists somewhere,
  -- which is an existence oracle for anyone who can call this.
  if org_loser is null or org_winner is null or org_loser <> org_winner then
    raise exception 'customer not found or not eligible for merge';
  end if;

  -- No chains. Reversal of a chain is ambiguous, and merging into the live
  -- survivor is always available instead.
  if loser_merged is not null or winner_merged is not null then
    raise exception 'one of these records has already been merged; merge into the surviving record instead';
  end if;

  -- ── consent delta, computed BEFORE anything moves ───────────────────────
  select coalesce(array_agg(a.consent::text order by a.consent), '{}')
    into flips
    from app_effective_consent(array[loser, winner]) a
    left join app_effective_consent(array[winner]) b on b.consent = a.consent
   where a.granted and coalesce(b.granted, false) = false;

  select coalesce(array_agg(a.consent::text order by a.consent), '{}')
    into withdrawals
    from app_effective_consent(array[loser, winner]) a
    left join app_effective_consent(array[winner]) b on b.consent = a.consent
   where a.granted = false and coalesce(b.granted, false) = true;

  select coalesce(array_agg(f order by f), '{}') into marketing_flips
    from unnest(flips) f where f like 'marketing_%';

  if array_length(marketing_flips, 1) > 0 and not confirm_marketing_flip then
    raise exception
      'this merge would make marketing consent effective where the surviving record had none: %. '
      'Re-run with confirm_marketing_flip => true if that is intended.',
      array_to_string(marketing_flips, ', ');
  end if;

  -- ── manifest, recorded BEFORE the move so reversal can replay it ─────────
  -- location_customer_access is NOT moved: its unique key is
  -- (organization_customer_id, location_id) where revoked_at is null, so moving
  -- would collide wherever both records were recognised at the same door.
  -- Instead the survivor is granted access at any door the loser could use and
  -- it could not, and the loser keeps its own rows — harmless, since nothing
  -- resolves to a tombstone any more.
  --
  -- identity_resolution moves only where it does not collide with its own
  -- unique key; a duplicate link to the same person_identity stays put and is
  -- recorded as skipped.
  select jsonb_build_object(
    'fitting_session', (select coalesce(jsonb_agg(id order by id), '[]'::jsonb)
                          from fitting_session where organization_customer_id = loser),
    'report',          (select coalesce(jsonb_agg(id order by id), '[]'::jsonb)
                          from report where organization_customer_id = loser),
    'follow_up',       (select coalesce(jsonb_agg(id order by id), '[]'::jsonb)
                          from follow_up where organization_customer_id = loser),
    'consent_record',  (select coalesce(jsonb_agg(id order by id), '[]'::jsonb)
                          from consent_record where organization_customer_id = loser),
    'identity_resolution', (select coalesce(jsonb_agg(id order by id), '[]'::jsonb)
                          from identity_resolution ir where ir.organization_customer_id = loser
                            and not exists (select 1 from identity_resolution w
                                             where w.organization_customer_id = winner
                                               and w.person_identity_id = ir.person_identity_id)),
    'identity_resolution_skipped', (select coalesce(jsonb_agg(id order by id), '[]'::jsonb)
                          from identity_resolution ir where ir.organization_customer_id = loser
                            and exists (select 1 from identity_resolution w
                                         where w.organization_customer_id = winner
                                           and w.person_identity_id = ir.person_identity_id))
  ) into manifest;

  update fitting_session      set organization_customer_id = winner where organization_customer_id = loser;
  update report               set organization_customer_id = winner where organization_customer_id = loser;
  update follow_up            set organization_customer_id = winner where organization_customer_id = loser;
  update consent_record       set organization_customer_id = winner where organization_customer_id = loser;
  update identity_resolution  set organization_customer_id = winner
   where id in (select jsonb_array_elements_text(manifest->'identity_resolution')::uuid);

  -- Grant the survivor access wherever the loser had it and the survivor did not.
  with granted as (
    insert into location_customer_access
      (organization_id, organization_customer_id, location_id, access_level, reason)
    select a.organization_id, winner, a.location_id, a.access_level,
           'granted by customer merge'
      from location_customer_access a
     where a.organization_customer_id = loser and a.revoked_at is null
       and not exists (select 1 from location_customer_access w
                        where w.organization_customer_id = winner
                          and w.location_id = a.location_id
                          and w.revoked_at is null)
    returning id)
  select manifest || jsonb_build_object(
           'location_access_granted', coalesce(jsonb_agg(id order by id), '[]'::jsonb))
    into manifest from granted;

  update organization_customer
     set merged_into_customer_id = winner, merged_at = now()
   where id = loser;

  insert into audit_log (organization_id, actor_user_id, actor_type, action,
                         subject_type, subject_id, target_type, target_id,
                         correlation_id, metadata)
  values (org_winner, actor, 'user', 'customer_identity.merge_completed',
          'organization_customer', winner, 'organization_customer', loser,
          correlation,
          jsonb_build_object(
            'moved', manifest,
            'consent_delta', jsonb_build_object(
               'flipped_to_granted',   to_jsonb(flips),
               'flipped_to_withdrawn', to_jsonb(withdrawals),
               'marketing_confirmed',  confirm_marketing_flip)));

  return manifest;
end $$ language plpgsql;

-- ── Reversal ────────────────────────────────────────────────────────────────
-- Replays the manifest exactly. Rows created after the merge are not in it and
-- stay with the survivor, because at the time they were written only one record
-- was live and they cannot honestly be attributed to either original.
create or replace function app_revert_customer_merge(
  loser uuid, actor uuid, correlation uuid)
returns jsonb as $$
declare
  org uuid; winner uuid; winner_merged uuid; manifest jsonb; restored jsonb;
begin
  select organization_id, merged_into_customer_id into org, winner
    from organization_customer where id = loser;
  if org is null or winner is null then
    raise exception 'customer not found or not eligible for merge';
  end if;

  select merged_into_customer_id into winner_merged
    from organization_customer where id = winner;
  if winner_merged is not null then
    raise exception 'the surviving record has itself been merged; unwinding a chain is ambiguous — use a forward correction instead';
  end if;

  select metadata->'moved' into manifest from audit_log
   where action = 'customer_identity.merge_completed'
     and subject_id = winner and target_id = loser
   order by seq desc limit 1;
  if manifest is null then
    raise exception 'no merge_completed audit row found for this pair; cannot reverse what was not recorded';
  end if;

  -- Clear the redirect FIRST. The fitting_session trigger refuses to attach a
  -- session to a tombstone, and during a reversal the destination is still one
  -- until this runs — the guard would otherwise block the very operation that
  -- un-tombstones the record.
  update organization_customer
     set merged_into_customer_id = null, merged_at = null
   where id = loser;

  -- Only rows still sitting on the survivor move back. One deleted in the
  -- meantime is a gap, recorded rather than fatal.
  update fitting_session set organization_customer_id = loser
   where organization_customer_id = winner
     and id in (select jsonb_array_elements_text(manifest->'fitting_session')::uuid);
  update report set organization_customer_id = loser
   where organization_customer_id = winner
     and id in (select jsonb_array_elements_text(manifest->'report')::uuid);
  update follow_up set organization_customer_id = loser
   where organization_customer_id = winner
     and id in (select jsonb_array_elements_text(manifest->'follow_up')::uuid);
  update consent_record set organization_customer_id = loser
   where organization_customer_id = winner
     and id in (select jsonb_array_elements_text(manifest->'consent_record')::uuid);
  update identity_resolution set organization_customer_id = loser
   where organization_customer_id = winner
     and id in (select jsonb_array_elements_text(manifest->'identity_resolution')::uuid);

  delete from location_customer_access
   where id in (select jsonb_array_elements_text(
                  coalesce(manifest->'location_access_granted', '[]'::jsonb))::uuid);

  select jsonb_build_object(
    'fitting_session_remaining', (select count(*) from fitting_session
       where organization_customer_id = winner
         and id in (select jsonb_array_elements_text(manifest->'fitting_session')::uuid)),
    'sessions_created_after_merge_kept_by_survivor', (select count(*) from fitting_session
       where organization_customer_id = winner)
  ) into restored;

  insert into audit_log (organization_id, actor_user_id, actor_type, action,
                         subject_type, subject_id, target_type, target_id,
                         correlation_id, metadata)
  values (org, actor, 'user', 'customer_identity.merge_reverted',
          'organization_customer', winner, 'organization_customer', loser,
          correlation, jsonb_build_object('restored', manifest, 'gaps', restored));

  return manifest;
end $$ language plpgsql;

-- ── Authority ───────────────────────────────────────────────────────────────
-- A merge rewrites six tables. It is an operator action through a service path,
-- not something a tablet session can invoke. Note that fitos_svc has BYPASSRLS,
-- so the explicit organization check inside the function — not RLS — is what
-- actually prevents a cross-tenant merge. Invoker rights are kept so that RLS
-- ALSO applies if this is ever called as fitos_app.
revoke execute on function app_merge_customer(uuid, uuid, uuid, uuid, boolean) from public;
revoke execute on function app_revert_customer_merge(uuid, uuid, uuid) from public;
grant  execute on function app_merge_customer(uuid, uuid, uuid, uuid, boolean) to fitos_svc;
grant  execute on function app_revert_customer_merge(uuid, uuid, uuid) to fitos_svc;
grant  execute on function app_resolve_customer(uuid) to fitos_app, fitos_svc;
grant  execute on function app_effective_consent(uuid[]) to fitos_app, fitos_svc;
grant  update (organization_customer_id) on fitting_session, report, follow_up,
  consent_record, identity_resolution to fitos_svc;
grant  update (merged_into_customer_id, merged_at) on organization_customer to fitos_svc;
grant  delete on location_customer_access to fitos_svc;


-- ═══════════════════════════════════════════════════════════════════════════
-- 0009_quick_intake.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- 0009 · quick intake
--
-- Pilot-store feedback: the intake is too long, and the associate wants yes/no
-- questions only. The default retail flow becomes three binary questions (two
-- for a returning customer) and then measurement.
--
-- ADDITIVE ONLY. Every existing intake column stays exactly as it is —
-- shopping_purpose, discomfort_area, fit_priority, standing_hours_per_day and
-- the rest are still written by the optional "Add detail" panel, and are still
-- read by the recommendation engine and the report. The default UX stops asking
-- for them; the schema has not lost the ability to hold them.
-- =============================================================================

alter table fitting_session
  -- Which intake produced this session. 'quick' is the new default; 'detailed'
  -- records that the associate opened Add detail, so time-to-scan can be
  -- compared honestly between the two.
  add column intake_mode text not null default 'quick'
    check (intake_mode in ('quick', 'detailed')),

  -- New-customer questions. Nullable on purpose: null means "not asked", which
  -- is not the same as "No". The report prints only what was answered.
  add column intake_discomfort         boolean,
  add column intake_shoe_issue         boolean,
  add column intake_high_activity      boolean,

  -- Returning-customer questions. Separate columns rather than reusing the
  -- three above: "any new pain SINCE YOUR LAST VISIT" is a different claim from
  -- "any discomfort today", and collapsing them would quietly corrupt both.
  add column intake_new_discomfort_since_last boolean,
  add column intake_use_changed_since_last    boolean,

  -- The metric the redesign is judged on. Seconds from the intake appearing to
  -- Start Scan being pressed. Sits alongside time_to_recommendation_ms, which
  -- already works this way.
  add column intake_duration_seconds integer
    check (intake_duration_seconds is null or intake_duration_seconds >= 0);

comment on column fitting_session.intake_mode is
  'quick = the three-question default; detailed = the associate opened Add detail.';
comment on column fitting_session.intake_duration_seconds is
  'Customer lookup complete to Start Scan pressed. Target 15-30s.';


-- ═══════════════════════════════════════════════════════════════════════════
-- 0010_customer_number_race.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- =============================================================================
-- 0010 · serialise per-retailer customer numbering
--
-- assign_local_customer_number() computed `max(local_customer_number) + 1` with
-- no lock. Two transactions inserting a customer for the same organization at
-- the same moment both read the same max and both write N+1, and the second one
-- fails on organization_customer_number_key.
--
-- In a store that is two associates at two tills creating a walk-in at the same
-- moment: rare, real, and it surfaces as an unexplainable error on the screen
-- that creates customers. It was found when a third test file began creating
-- customers concurrently and the suite started failing about one run in three.
--
-- The fix is a transaction-scoped advisory lock keyed on the organization, so
-- numbering serialises per retailer and never across retailers. Released
-- automatically at commit or rollback; nothing to leak.
-- =============================================================================

create or replace function assign_local_customer_number() returns trigger as $$
begin
  if new.local_customer_number is null or new.local_customer_number = 0 then
    perform pg_advisory_xact_lock(
      hashtext('organization_customer_number'), hashtext(new.organization_id::text));
    select coalesce(max(local_customer_number), 0) + 1
      into new.local_customer_number
      from organization_customer
     where organization_id = new.organization_id;
  end if;
  return new;
end $$ language plpgsql;


-- ─────────────────────────────────────────────────────────────────────────────
commit;

-- Sanity check. Run this after committing; it should report 29 tables and every
-- one of the RLS numbers non-zero.
--   select count(*) tables from pg_class c join pg_namespace n on n.oid=c.relnamespace
--    where n.nspname='public' and c.relkind='r';
--   select count(*) rls_forced from pg_class where relforcerowsecurity;
--   select count(*) policies from pg_policies where schemaname='public';
